#+TITLE:     org-page: static page generator
#+AUTHOR:    Kelvin Hu
#+EMAIL:     ini.kelvin@gmail.com
#+DATE:      2012-08-23
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t


* Introduction

  Org-page is a static page generator based on [[http://orgmode.org/][org-mode]].

  From v0.3, org-page is not just an enhancement for org publish process, since
  org publish process is designed for general publication, it is not only for
  html generation. But what we need, is only html generation with highly
  customized configuration.

  Org-page provides following features:

  1) org sources and html files managed by git
  2) incremental publication (according to =git diff= command)
  3) tags support (auto generated)
  4) search engine support (auto generated)
  5) a much more beautiful theme than the default one
  6) theme customization support
  7) commenting (implemented using disqus)
  8) index/about page support (auto generated if no default provided)
  9) highly customizable

  [[http://kelvinh.github.com][Here]] is a demo site generated by org-page.

** Workflow

   1. you specify a git repo, where org sources on its "source" branch (the
      branch name can be customized, the same below), and generated html files
      on its "master" branch
   2. you specify a "base commit" (previouse commit will be used if omitted),
      org-page will read changes between the latest commit and the specified
      base commit on branch "source", the changes will be published
   3. org-page does preparation jobs
   4. publish the changes read in step 2, a change can be an addition, a
      modification, or a deletion, *org-page is designed to handle all these
      kinds of changes, but currently deletion is not implemented*
      - org-page will separate all sources into two categories: "blog" and
        "wiki", a file belongs to which category depends on its folder name
      - the uri path of generated html depends on =#+URI= option in org file
   5. update blog/wiki index pages, tag pages
   6. publication finished

* Usage

** installation

   clone the repo from github:

   : git clone http://github.com/kelvinh/org-page.git

** configuration

   add following lines into your =.emacs= file:

   : (add-to-list 'load-path "path/to/org-page")
   : (require 'org-page)
   : (setq op/repository-directory "path/to/your/org/repository")
   : (setq op/site-url "http://your.personal.site.com/")
   : (setq op/personal-disqus-shortname "your_disqus_shortname")
   : (setq op/repository-org-branch "your_org_branch_name")
   : (setq op/repository-html-branch "your_html_branch_name")

** publication

   evaluate following code to do publication:

   : (op/do-publication "HEAD^1" "~/org-pub/" nil)

   or just

   : (op/do-publication)

  For the usage of the variables and function above, please see their
  documentation, please make good use of your =C-h f= and =C-h v=. :-)

* Dependencies

  1. [[http://www.gnu.org/software/emacs/][Emacs]]: this is an "of-course" dependency
  2. [[http://orgmode.org/][org mode]]: which is already included in Emacs
  3. [[http://git-scm.com][git]]: a free and open source version control system

* Known issues

  - Currently the RSS feature has not been implemented, so the RSS link is
    unavailable.
  - Currently the deletion change handler has not been implemented, so if you
    deleted some org sources, you may have to manually delete corresponding
    html files generated.
  - URI path change detection is not available, that is, if you make a post
    with URI "/blog/2013/03/25/the-old-post-name", then you changed it in your
    org source (with new value of =#+URI= property), org-page is unable to
    detect this kind of change, it will only publish a new html file for you,
    so you need to delete the old html file related to the old URI manually.

* Additional information

  For more customization info, please see the =Commentary= section in
  file =org-page.el= and =op-vars.el=.
