#+TITLE:       关于
#+AUTHOR:      Kelvin Hu
#+EMAIL:       ini.kelvin@gmail.com
#+DATE:        2012-11-27 Tue
#+KEYWORDS:    about page, personal site
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t
#+DESCRIPTION: This is the about page of http://kelvinh.github.com/

Hello, I am Kelvin Hu, from China, you could get in touch with me through the
following ways:
- [[mailto: ini <dot> kelvin <at> gmail <dot> com][Email]] (please replace corresponding characters)
- [[https://github.com/kelvinh][GitHub]]
- [[http://weibo.com/ikevinhu][Sina Weibo]]
- [[https://twitter.com/__kelvinh__][Twitter]] (not used very often)

* About me

  I like programming, sports, music. For a more funny and detailed description
  about me, please see the section [[*%E5%85%B3%E4%BA%8E%E6%88%91][About me]] in Chinese.

* About this site

  This site is generated by [[http://github.com/kelvinh/org-page][org-page]], I only wrote the source org files, then
  it generated all things I want.

  It is highly recommended to give it a try if you are also an Emacs and org
  mode user.

* Thanks

  Really thank @<strong>Lenin Lee, the owner of site [[http://0x3f.org]]@</strong>,
  I borrowed the styles from his site, and then did some customization based
  on it.

-------------------------------------------------------------------------------

大家好，我是Kelvin Hu，来自大天朝，你可以通过以下方式联系我：
- [[mailto: ini <dot> kelvin <at> gmail <dot> com][Email]] （请替换相应的字符）
- [[https://github.com/kelvinh][GitHub]]
- [[http://weibo.com/ikevinhu][新浪微博]]
- [[https://twitter.com/__kelvinh__][Twitter]] （不怎么常用）

* 关于我

  接近90后，HUST打铁专业毕业，但目前是软贱攻城湿一枚，坐标南京。

  高穷帅，轻度洁癖，轻度强迫症，不折腾会死星人，兴趣广泛，好奇心能害死猫。

** 编程

   从打铁专业过来编程，平时写一些Python，Elisp。工作时什么都写（所在公司项目有点奇葩，目前
   主流编程语言除了汇编和Ruby没有用到外，其它全部都有涉及，包括令人蛋疼的Windows批处理）。

** 运动

   爱好运动，包括但不限于篮球(瘦高型中锋)，乒乓球，游泳。

** 音乐

   略懂音律，略懂横笛。（真的只是“略懂”）

* 关于本站

  本站是使用[[http://github.com/kelvinh/org-page][org-page]]生成的，我只是写了org文件，然后，它就帮我把一切都生成好了。

  如果你也使用Emacs/org mode，非常建议你试一试。

* 感谢

  非常感谢@<strong>Lenin Lee, [[http://0x3f.org]]的站长@</strong>，鉴于本人那糟糕的设计天赋，以及可怜
  的CSS知识，我就直接从他的站点“借”来了样式，然后在这个基础上做了一些自定义。
